#!/bin/sh

while :;
do
    echo 1 > /sys/devices/platform/applesmc.768/fan1_manual
    cat /sys/devices/platform/applesmc.768/fan1_min > /sys/devices/platform/applesmc.768/fan1_output
    sleep 0.3
done
